import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./_components/providers";
import "./globals.css";
import { authOptions } from "@/lib/auth/auth-options";
import "leaflet/dist/leaflet.css";
import "leaflet-control-geocoder/dist/Control.Geocoder.css";

const inter = Inter({ subsets: ["latin"] });

// App usa auth (headers/cookies) — evita erros de geração estática no build
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
	title: "OpenGD",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="pt-BR">
			<body className={`${inter.className}`}>
				<Providers session={session}>
					{children}
					<Toaster richColors theme="light" closeButton />
				</Providers>
			</body>
		</html>
	);
}
